modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/GTLugo/ampere/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo-large.png"

[[dependencies.ampere]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ampere]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ampere]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ampere.mixins.json"
